### ISSUE TITLE
Make VarIntError implement core::error::Error

### ISSUE THREAD

**Issue by ianthetechie** [arnohaase/bytes-varint#1]
Thanks for the wonderful crate! I'm currently using it on a project and it's been great so far.

I noticed that the `VarIntError` doesn't implement the `Error` trait. This makes error handling somewhat clunky.

I assume that the reason this is not currently implemented is the desire to keep `no_std` compatibility. Prior to Rust 1.81, the `Error` trait was only available via an `std::error` re-export of the (then-unstable) `core::error::Error`.

Since 1.81, [`core::error::Error`](https://doc.rust-lang.org/nightly/core/error/index.html) is stable, so you can preserve `no_std` compatibility while adding `Error` trait conformance. If you'd prefer not requiring such a recent compiler version, then perhaps you would be OK with either making the conformance optional (ex: by making a `no_std` feature which is enabled by default or by adding a `core_error` feature that's disabled by default and requires Rust 1.81+), or using something like [rustversion](https://github.com/dtolnay/rustversion) to automatically include the conformance on available compilers.

**Comment by arnohaase** [comment]
Thank you for the feedback and the thorough discussion of options! I've 
been feeling the awkwardness of not implementing Error myself, and I 
think I'll go for requiring 1.81 in the new crate version - most 
projects update to the latest rust toolchain anyway, and if they don't, 
they can still use the older version.



Am 21.10.24 um 05:57 schrieb Ian Wagner:

**Comment by arnohaase** [comment]
I just released version 1.1.0, addressing this issue and some other 
things that have been on my mind for a while. Feedback is welcome!

Am 21.10.24 um 05:57 schrieb Ian Wagner:

**Comment by ianthetechie** [comment]
Wow, what a quick turnaround 😂  I just gave it a spin after upgrading and it works as intended :)

**Comment by arnohaase** [comment]
:-)

Am 21.10.24 um 15:50 schrieb Ian Wagner:
